### ISSUE TITLE
MP/Incoming damage numbers

### ISSUE THREAD

**Issue by brnbrito** [Tera-Shiraneko/no-healing-numbers#1]
Would it be possible to remove MP and incoming damage numbers as well?

**Comment by Tera-Shiraneko** [comment]
Yeah its possible but there is also an setting for the mp number hiding in the game. Guess I will make extra mod or add it to this one.

**Comment by brnbrito** [comment]
Yeah the in-game option seems to work fine but mystics still got the -MP popups every second from auras, will recheck when servers are up again, thank you for the update! :)

**Comment by Tera-Shiraneko** [comment]
Like I said in the readme I cant remove everything.
